/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_phash_pHash */

#ifndef _Included_org_phash_pHash
#define _Included_org_phash_pHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_phash_pHash
 * Method:    videoHash
 * Signature: (Ljava/lang/String;)Lorg/phash/VideoHash;
 */
JNIEXPORT jobject JNICALL Java_org_phash_pHash_videoHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_phash_pHash
 * Method:    audioHash
 * Signature: (Ljava/lang/String;)Lorg/phash/AudioHash;
 */
JNIEXPORT jobject JNICALL Java_org_phash_pHash_audioHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_phash_pHash
 * Method:    dctImageHash
 * Signature: (Ljava/lang/String;)Lorg/phash/DCTImageHash;
 */
JNIEXPORT jobject JNICALL Java_org_phash_pHash_dctImageHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_phash_pHash
 * Method:    mhImageHash
 * Signature: (Ljava/lang/String;)Lorg/phash/MHImageHash;
 */
JNIEXPORT jobject JNICALL Java_org_phash_pHash_mhImageHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_phash_pHash
 * Method:    mhImageHashFromPixels
 * Signature: ([BIII)Lorg/phash/MHImageHash;
 */
JNIEXPORT jobject JNICALL Java_org_phash_pHash_mhImageHashFromPixels
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     org_phash_pHash
 * Method:    radialImageHash
 * Signature: (Ljava/lang/String;)Lorg/phash/RadialImageHash;
 */
JNIEXPORT jobject JNICALL Java_org_phash_pHash_radialImageHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_phash_pHash
 * Method:    textHash
 * Signature: (Ljava/lang/String;)Lorg/phash/TextHash;
 */
JNIEXPORT jobject JNICALL Java_org_phash_pHash_textHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_phash_pHash
 * Method:    imageDistance
 * Signature: (Lorg/phash/ImageHash;Lorg/phash/ImageHash;)D
 */
JNIEXPORT jdouble JNICALL Java_org_phash_pHash_imageDistance
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_phash_pHash
 * Method:    audioDistance
 * Signature: (Lorg/phash/AudioHash;Lorg/phash/AudioHash;)D
 */
JNIEXPORT jdouble JNICALL Java_org_phash_pHash_audioDistance
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_phash_pHash
 * Method:    videoDistance
 * Signature: (Lorg/phash/VideoHash;Lorg/phash/VideoHash;I)D
 */
JNIEXPORT jdouble JNICALL Java_org_phash_pHash_videoDistance
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     org_phash_pHash
 * Method:    textDistance
 * Signature: (Lorg/phash/TextHash;Lorg/phash/TextHash;)I
 */
JNIEXPORT jint JNICALL Java_org_phash_pHash_textDistance
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_phash_pHash
 * Method:    pHashInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_phash_pHash_pHashInit
  (JNIEnv *, jclass);

/*
 * Class:     org_phash_pHash
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_phash_pHash_cleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
